Traceback (most recent call last):
  File "MainKratos.py", line 37, in <module>
    simulation.Run()
  File "/home/julio/GiDx64/14.0.5/problemtypes/kratos.gid/exec/Kratos/kratos/python_scripts/analysis_stage.py", line 47, in Run
    self.Initialize()
  File "/home/julio/GiDx64/14.0.5/problemtypes/kratos.gid/exec/Kratos/kratos/python_scripts/analysis_stage.py", line 68, in Initialize
    self._GetSolver().ImportModelPart()
  File "/home/julio/GiDx64/14.0.5/problemtypes/kratos.gid/exec/Kratos/applications/convection_diffusion_application/python_scripts/coupled_fluid_thermal_solver.py", line 68, in ImportModelPart
    self.fluid_solver.ImportModelPart()
  File "/home/julio/GiDx64/14.0.5/problemtypes/kratos.gid/exec/Kratos/applications/FluidDynamicsApplication/python_scripts/fluid_solver.py", line 61, in ImportModelPart
    self._ImportModelPart(self.main_model_part,self.settings["model_import_settings"])
  File "/home/julio/GiDx64/14.0.5/problemtypes/kratos.gid/exec/Kratos/kratos/python_scripts/python_solver.py", line 160, in _ImportModelPart
    KratosMultiphysics.ModelPartIO(input_filename, import_flags).ReadModelPart(model_part)
RuntimeError: Error: the condition with Id 0 does not exist in the root model part




in kratos/sources/model_part.cpp:1261:void ModelPart::AddConditions(const vector<long unsigned int>&, ModelPart::IndexType)
   kratos/sources/model_part.cpp:1275:void ModelPart::AddConditions(const vector<long unsigned int>&, ModelPart::IndexType)
   kratos/sources/model_part_io.cpp:3239:void ModelPartIO::ReadSubModelPartConditionsBlock(ModelPart&, ModelPart&)
   kratos/sources/model_part_io.cpp:3058:void ModelPartIO::ReadSubModelPartBlock(ModelPart&, ModelPart&)
   kratos/sources/model_part_io.cpp:526:virtual void ModelPartIO::ReadModelPart(ModelPart&)

